### PR TITLE
Update to Atom new API

### PR DESCRIPTION
**Pull request by pandres95**

### CODE REVIEW

**Comment by guileen** [comment]
Hi, I use vim again, and I am not using atom any more. So currently this project is not maintained.

I wonder if you have any interesting to maintain this project, I can add you to the collobrators

**Comment by pandres95** [comment]
I am interested in maintain this project :)

**Comment by guileen** [comment]
I have add you to collaborators, but I don't know how to grant you the permission of publish this package to atom.

**Comment by pandres95** [comment]
According to Atom's [documentation](https://atom.io/docs/v0.74.0/publishing-a-package), we don't need any other access than the permissions to push into the repository.

**Comment by guileen** [comment]
Awesome.

**Comment by pandres95** [comment]
@guileen `apm` is asking me for the API Token. Maybe I just need this :smile:

**Comment by guileen** [comment]
I don't know the API Token, I think you don't need that, my another package `project-switcher` has invite @ricardofbarros to maintain it, and he has published a new version without API Token, Maybe you can ask him about publishing.

 https://github.com/guileen/project-switcher/releases/tag/v0.1.3

**Comment by pandres95** [comment]
There was no problem. I finally could publish de package. npm gave me an API Token.

**Comment by guileen** [comment]
:ok:

**Pull request merged**
